version: "3.9"
services:
  web:
    build: ./infra/php
    volumes:
      - ./src:/data
    depends_on:
      - db

  nginx:
    image: nginx:1.20-alpine
    ports:
      - "8080:80"
    volumes:
      - ./src:/data
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /data

  db:
    build: ./infra/mysql
    ports:
      - "13306:3306"
    volumes:
      - db-store:/var/lib/mysql

volumes:
  db-store: