name: Laravel Testing

on:
  pull_request:

jobs:
  laravel-testing:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Docker Version
        run: docker version

      - name: Build Docker Images
        run: docker-compose -f docker-compose-test.yml build

      - name: Create & Start Docker Containers
        run: docker-compose -f docker-compose-test.yml up -d

      - name: OS Version
        run: |
          docker-compose -f docker-compose-test.yml exec -T web cat /etc/os-release
          docker-compose -f docker-compose-test.yml exec -T web cat /etc/debian_version

      - name: PHP Version
        run: docker-compose -f docker-compose-test.yml exec -T web php --version

      - name: Composer Version
        run: docker-compose -f docker-compose-test.yml exec -T web composer --version

      - name: Install Dependencies
        run: docker-compose -f docker-compose-test.yml exec -T web composer install

      - name: Laravel Version
        run: docker-compose -f docker-compose-test.yml exec -T web php artisan --version

      - name: Laravel Setting
        run: |
          docker-compose -f docker-compose-test.yml exec -T web cp .env.example .env
          docker-compose -f docker-compose-test.yml exec -T web php artisan key:generate

      - name: Laravel Migrate Testing
        run: docker-compose -f docker-compose-test.yml exec -T web php artisan migrate

      - name: Laravel Rollback Testing
        run: docker-compose -f docker-compose-test.yml exec -T web php artisan migrate:refresh

      - name: Laravel Seeding Testing
        run: docker-compose -f docker-compose-test.yml exec -T web php artisan db:seed

      - name: Laravel PHPUnit Testing
        run: docker-compose -f docker-compose-test.yml exec -T web php artisan test

      - name: CodeSniffer Testing
        run: docker-compose -f docker-compose-test.yml exec -T web composer sniffer